public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_salario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        tbox_salario = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        lbl_fechaIngreso = new javax.swing.JLabel();
        lbl_meses1 = new javax.swing.JLabel();
        lbl_anio1 = new javax.swing.JLabel();
        lbl_anio2 = new javax.swing.JLabel();
        lbl_fechaRetiro = new javax.swing.JLabel();
        JS_dia_fechaRetiro = new javax.swing.JSpinner();
        JS_anio_fechaRetiro = new javax.swing.JSpinner();
        lbl_dia2 = new javax.swing.JLabel();
        lbl_meses2 = new javax.swing.JLabel();
        lbl_presuspuestado = new javax.swing.JLabel();
        ckPreavisado = new javax.swing.JCheckBox();
        JS_meses_fechaRetiro = new javax.swing.JSpinner();
        JS_anio_fechaIngreso = new javax.swing.JSpinner();
        JS_meses_fechaIngreso = new javax.swing.JSpinner();
        JS_dia_fechaIngreso = new javax.swing.JSpinner();
        lbl_dia1 = new javax.swing.JLabel();
        btnCalcular1 = new javax.swing.JButton();
        lbl_presuspuestado1 = new javax.swing.JLabel();
        ckVacaciones = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Prestaciones V1 - Edwin Alberto Roman");
        setResizable(false);

        lbl_title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_title.setText("Calculadora de Prestaciones Laborales");

        lbl_salario.setText("Salario:");

        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        tbox_salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbox_salarioActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lbl_fechaIngreso.setText("Fecha Ingreso:");

        lbl_meses1.setText("Mes");

        lbl_anio1.setText("Año");

        lbl_anio2.setText("Año");

        lbl_fechaRetiro.setText("Fecha Retiro:");

        JS_dia_fechaRetiro.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 31.0d, 1.0d));

        JS_anio_fechaRetiro.setModel(new javax.swing.SpinnerNumberModel(1990.0d, 1990.0d, null, 1.0d));

        lbl_dia2.setText("Día");

        lbl_meses2.setText("Mes");

        lbl_presuspuestado.setText("¿Tomó usted  las vacaciones correspondientes al último año?");

        ckPreavisado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPreavisadoActionPerformed(evt);
            }
        });

        JS_meses_fechaRetiro.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 12.0d, 1.0d));

        JS_anio_fechaIngreso.setModel(new javax.swing.SpinnerNumberModel(1990.0d, 1990.0d, null, 1.0d));

        JS_meses_fechaIngreso.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 12.0d, 1.0d));

        JS_dia_fechaIngreso.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 31.0d, 1.0d));

        lbl_dia1.setText("Día");

        btnCalcular1.setText("Calcular");
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });

        lbl_presuspuestado1.setText("¿Fue usted  preavisado?");

        ckVacaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckVacacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(lbl_salario))
                            .addComponent(tbox_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(lbl_fechaIngreso))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lbl_dia1)
                                .addGap(65, 65, 65)
                                .addComponent(lbl_meses1)
                                .addGap(81, 81, 81)
                                .addComponent(lbl_anio1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(JS_dia_fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(JS_meses_fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(JS_anio_fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(lbl_fechaRetiro))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lbl_dia2)
                                .addGap(75, 75, 75)
                                .addComponent(lbl_meses2)
                                .addGap(71, 71, 71)
                                .addComponent(lbl_anio2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(JS_dia_fechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(JS_meses_fechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(JS_anio_fechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_presuspuestado1)
                                .addGap(13, 13, 13)
                                .addComponent(ckPreavisado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_presuspuestado)
                                .addGap(18, 18, 18)
                                .addComponent(ckVacaciones)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCalcular1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_title)
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_title)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_salario)
                        .addGap(9, 9, 9)
                        .addComponent(tbox_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(lbl_fechaIngreso)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_dia1)
                            .addComponent(lbl_meses1)
                            .addComponent(lbl_anio1))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JS_dia_fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JS_meses_fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JS_anio_fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(lbl_fechaRetiro)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_dia2)
                            .addComponent(lbl_meses2)
                            .addComponent(lbl_anio2))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JS_dia_fechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JS_meses_fechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JS_anio_fechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_presuspuestado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckVacaciones))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_presuspuestado1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckPreavisado)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(btnCalcular1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbox_salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbox_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbox_salarioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtArea.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void ckPreavisadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPreavisadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckPreavisadoActionPerformed

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
        iniciador();
    }//GEN-LAST:event_btnCalcular1ActionPerformed

    private void ckVacacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckVacacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckVacacionesActionPerformed
    
    private void iniciador(){
        
        addSueldo();
        addFechaIngreso();
        addFechaRetiro();
        calculador = new CalculadorPrestaciones(empleado);
        
        //Para verificar con el check
        calculador.checkEstadoPreaviso(ckPreavisado.isSelected());
        calculador.checkEstadoVacaciones(ckVacaciones.isSelected());
        calculador.calculoPrestacionCesantia();
        calculador.calculoRegaliaPascual();
        
        showInfo();
    }
    
    private void addSueldo(){
        double salario = Double.valueOf(this.tbox_salario.getText());
        
        if(salario < 0 || "".equals(this.tbox_salario.getText())){
            salario = 0;
        }
        else{
            empleado.setSalario(salario);
        }
        
    }
    
    private void addFechaIngreso(){
        double dia = (Double)(JS_dia_fechaIngreso.getValue());
        double mes = (Double)(JS_meses_fechaIngreso.getValue());
        double anio = (Double)(JS_anio_fechaIngreso.getValue());

        double[] fechaEntrada = {dia, mes, anio};
        empleado.setFechaEntrada(fechaEntrada);
    }
    
    private void addFechaRetiro(){
        double dia = (Double)(JS_dia_fechaRetiro.getValue());
        double mes = (Double)(JS_meses_fechaRetiro.getValue());
        double anio = (Double)(JS_anio_fechaRetiro.getValue());

        double[] fechaRetiro = {dia, mes, anio};
        empleado.setFechaSalida(fechaRetiro);
    }
    
    private void showInfo(){
        this.txtArea.append("Resultados: \n");
        this.txtArea.append("Sueldo Promedio: $" + Math.round(calculador.getSalarioPromedioMensual()*100.0)/100.0);
        this.txtArea.append("\nSalario Díario: $" + Math.round(calculador.getSalarioDiario()*100.0)/100.0);
        this.txtArea.append("\nPreaviso: $" + Math.round(calculador.getPrestacionPreaviso()*100.0)/100.0);
        this.txtArea.append("\nCesantia: $" + Math.round(calculador.getPrestacionCesantia()*100.0)/100.0);
        this.txtArea.append("\nVacaciones: $" + Math.round(calculador.getPrestacionVacacional()*100.0)/100.0); 
        this.txtArea.append("\nRegalia Pascual: $" + Math.round(calculador.getRegaliaPascual()*100.0)/100.0);
        this.txtArea.append("\n\nTotal Prestaciones: $" + Math.round(calculador.getPrestacionPreaviso() + calculador.getPrestacionCesantia() + calculador.getPrestacionVacacional() + calculador.getRegaliaPascual() *100.0)/100.0);

        this.txtArea.append("\n" + calculador.inpretacion());

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    Empleado empleado = new Empleado();
    CalculadorPrestaciones calculador;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner JS_anio_fechaIngreso;
    private javax.swing.JSpinner JS_anio_fechaRetiro;
    private javax.swing.JSpinner JS_dia_fechaIngreso;
    private javax.swing.JSpinner JS_dia_fechaRetiro;
    private javax.swing.JSpinner JS_meses_fechaIngreso;
    private javax.swing.JSpinner JS_meses_fechaRetiro;
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox ckPreavisado;
    private javax.swing.JCheckBox ckVacaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_anio1;
    private javax.swing.JLabel lbl_anio2;
    private javax.swing.JLabel lbl_dia1;
    private javax.swing.JLabel lbl_dia2;
    private javax.swing.JLabel lbl_fechaIngreso;
    private javax.swing.JLabel lbl_fechaRetiro;
    private javax.swing.JLabel lbl_meses1;
    private javax.swing.JLabel lbl_meses2;
    private javax.swing.JLabel lbl_presuspuestado;
    private javax.swing.JLabel lbl_presuspuestado1;
    private javax.swing.JLabel lbl_salario;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField tbox_salario;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
